Update Lite-GPT link
fmhy/edit pull request #2434
Opened 2024-09-30 06:53 UTC by helix-nuked

The new owner has set the URL to `link.fuckicoding.com`

## Description

I got email from lite-gpt that the owner was changed
PS: I don't know what happen down there of the code but i was editing directly from GitHub editor

## Context

URL

## Types of changes

- [ x ] Bad / Deleted sites removal
- [ ] Grammar / Markdown fixes 
- [ ] Content addition (sites, projects, tools, etc.)
- [ ] New Wiki section

## Checklist:

- [ ] I have read the [contribution guide](https://fmhy.net/other/contributing).
- [ x ] I have made sure to [search](https://api.fmhy.net/single-page) before making any changes. 
- [ x ] My code follows the code style of this project.

2024-09-30 12:02 UTC, Setsuwaa requested changes
change "http" to "https" please

2024-09-30 12:08 UTC, helix-nuked commented
oh ok one sec

Sent from Proton Mail Android

-------- Original Message --------
On 9/30/24 5:03 PM, Isabella Tsaniia  wrote:

> @Setsuwaa requested changes on this pull request.
>
> change "http" to "https" please
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/fmhy/edit/pull/2434#pullrequestreview-2337303078), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/BK6DLRK472EPZ4LC7IZQRCLZZE4XNAVCNFSM6AAAAABPCSVZWSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGMZXGMYDGMBXHA).
> You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-09-30 12:10 UTC, helix-nuked commented
> edit: ignore original comment, why is this site not HTTPS
> 
> Is there any sign of this site being upgraded to HTTPS in the near future?

i don't know

2024-09-30 12:18 UTC, helix-nuked commented
I added warning

2024-09-30 23:03 UTC, merged

2024-10-01 00:56 UTC, Setsuwaa commented
sorry late reply, looks good to me :3

2024-10-01 04:38 UTC, helix-nuked commented
lets goo first merged pr eveeer

2024-10-02 17:12 UTC, helix-nuked commented
one more comment and it
> secretly fits to issue comments number